### ISSUE TITLE
Welcome to the Dragonet Forums

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonetForums#1]
## Welcome!! This is Dragonet Forums

**We are sorry that we can't create a website for this because we are lack of fund. :( **

### Tutorial
Well, the Github issue system can work like a forum too. 
- To create a topic, simply click `New Issue`. 
- To reply to a topic, just reply to the issue and tag someone(like @DefinitlyEvil). 
- To edit/delete a topic, click the icon right near your reply/topic's title bar. 
- To end the discussion, close the issue. Otherwise, do not close it or it can't be seen directly in the list.

**Comment by TheMCPEGamer** [comment]
@DefinitlyEvil Sometime in the future, I may be able to host a webserver, as I am building my own personal computer/HTPC

http://pcpartpicker.com/p/6zV6bv

**Comment by DefinitlyEvil** [comment]
We have to get a webserver which can defense DDoS attack.

**Comment by QuarkTheAwesome** [comment]
Technically you could use GitHub Pages in combination with something like [Jekyll Disqus](http://klcodanr.github.io/Jekyll-Disqus-Forum/) or just use a free webhost ([like I do](http://quarktheawesome.ml)). The only downside of a free webhost (or at least the one I use) is that you can't use any form of JavaScript, lest your users be redirected. However, avoiding JavaScript and being careful with my cross-site scripting has made a completely ad-free site that literally cost me nothing.

**Comment by DefinitlyEvil** [comment]
Trying. ;)

**Comment by QuarkTheAwesome** [comment]
(Just thought I'd mention that I personally recommend going the free webhost path so you can have PHP and all the dynamic page magic that provides)

Trying?

**Comment by DefinitlyEvil** [comment]
Free hosting always down. xD @QuarkTheAwesome

**Comment by QuarkTheAwesome** [comment]
@DefinitlyEvil Heh, if you think so. In my experience, however, I've only ever had my website go down once over the 2-3 years I've been working on it, and that was only for a few hours. Never the less, you guys have already set up Jekyll Discus so it doesn't matter that much anyway. ;3

**Comment by RandomAltThing** [comment]
@TheMCPEGamer *Cough* MyBB *cough*

**Comment by RandomAltThing** [comment]
I like the insanityservers.net theme

**Comment by RandomAltThing** [comment]
I'm not collaborator here :P

**Comment by DefinitlyEvil** [comment]
@RandomAltThing You are a part of the organization. :3

**Comment by RandomAltThing** [comment]
@DefinitelyEvil But I'm a team which doesn't have access to all repositories, only certain ones. It would be nice to be in owner but I don't contribute much code as I'm very busy.

**Comment by RandomAltThing** [comment]
@DefinitlyEvil

**Comment by DefinitlyEvil** [comment]
@RandomAltThing I will give you perms if you need to commit any changes. ;)

**Comment by RandomAltThing** [comment]
@DefinitlyEvil Probably not this website looks complicated :P I have perms for the main code so its all good. Btw what's the server IP if you finally set it up?

**Comment by DefinitlyEvil** [comment]
@RandomAltThing Test server isn't ready yet, they gave me a wrong login password. xD

**Comment by DefinitlyEvil** [comment]
@TekkitCommando
