### ISSUE TITLE
Proclaiming of Copyrights

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonetForums#2]
## Recently, we've received a notice from a Chinese website that someone tried to fake me(the leader of our team, <a href="http://github.com/DefinitlyEvil">@DefinitlyEvil</a>). 
We've looked into this case and we discovered following things did by that person: 
* Faking <a href="http://github.com/DefinitlyEvil">@DefinitlyEvil</a>
* Creating non-approved topic at <a href="http://www.mcbbs.net/thread-373763-1-1.html">http://www.mcbbs.net/thread-373763-1-1.html</a>
* Creating donation link to gather money for himself/herself.

**Comment by gaoyichuan** [comment]
Well, that post is already deleted now.
